### ISSUE TITLE
ubuntu下无法运行

### ISSUE THREAD

**Issue by TheSlientnight** [wgpsec/VulnRange#1]
感觉文档有点粗略，python需要用到的模块都没有安装，导致搭建后各种报错
![image](https://user-images.githubusercontent.com/37974664/94640952-8a543080-0312-11eb-81f0-cde4f8c11431.png)
![image](https://user-images.githubusercontent.com/37974664/94641007-ae177680-0312-11eb-9081-5b004417cbae.png)

**Comment by VerInfinity** [comment]
缺少db模块，装了还是不行，感觉有可能是代码写的有问题from .import db,大佬帮忙看下是不是哪里有问题还是缺少模块
![image](https://user-images.githubusercontent.com/51886331/97780709-35316600-1bc1-11eb-95c4-dfa29322c644.png)
![image](https://user-images.githubusercontent.com/51886331/97780717-49756300-1bc1-11eb-9bb8-eb20a0284005.png)

**Comment by 0xf4n9x** [comment]
Python版本更新高一点试试，我这边一开始3.6版本无法使用，后来更新到了3.8就行了。

**Comment by keac** [comment]
在文档下面有注意事项说明，Python版本需要更新到3.8

**Comment by wintrysec** [comment]
我开发时用的较高版本的Python3.8，DB报错升级python版本即可，Flask 报错 更新pip源后，重新安装Flask框架即可 pip install Flask
