### ISSUE TITLE
web界面可以访问，启动靶场环境后，默认都是指向80端口，请问是什么原因

### ISSUE THREAD

**Issue by flow8008** [wgpsec/VulnRange#3]
是因为docker没有开起来吗？
![image](https://user-images.githubusercontent.com/76170795/111473449-037efd00-8766-11eb-8c23-e2e6311ae420.png)
![image](https://user-images.githubusercontent.com/76170795/111473589-2a3d3380-8766-11eb-807a-0ac013941063.png)
![image](https://user-images.githubusercontent.com/76170795/111473622-3628f580-8766-11eb-81f3-96cea4270b88.png)

**Comment by wintrysec** [comment]
端口都没给出来，应该是Docker启动报错了，看下报错信息
